name: fiboeda
description: Fibonacci Delivery App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_brand_icons: any
  url_launcher: any
  badges: any
  shared_preferences: any
  provider: any
  firebase_core: any
  cloud_firestore: any
  carousel_slider: any
  auto_size_text: any
  flutter_spinbox: any

flutter:
  uses-material-design: true
  assets:
    - assets/
